apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
  labels:
    app: {{ .Chart.Name }}-app
spec:
  ports:
    - port: {{ .Values.app.servicePort }}
      targetPort: {{ .Values.app.servicePort }}
  selector:
    app: {{ .Chart.Name }}-app
